In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
np.random.seed(42)
X = np.random.randint(3, 10, (9, 2))
C = np.array([[1], [3]])
print(X)
print(np.linalg.norm((X[:, np.newaxis, :] - C), axis=2))

print((X[:, np.newaxis, :] - C).shape)

[[9 6]
 [7 9]
 [5 7]
 [7 9]
 [4 5]
 [9 5]
 [5 7]
 [6 5]
 [8 7]]
[[ 9.43398113  6.70820393]
 [10.          7.21110255]
 [ 7.21110255  4.47213595]
 [10.          7.21110255]
 [ 5.          2.23606798]
 [ 8.94427191  6.32455532]
 [ 7.21110255  4.47213595]
 [ 6.40312424  3.60555128]
 [ 9.21954446  6.40312424]]
(9, 2, 2)


In [23]:
data = {        # Initialize data
    "Index" : [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "Age" : [18, 20, 22, 30, 34, 40, 60, 66, 70],
    "Expenditure": [80, 90, 85, 50, 64, 60, 30, 40, 25]
}

df = pd.DataFrame(data)

print(df)

   Index  Age  Expenditure
0      1   18           80
1      2   20           90
2      3   22           85
3      4   30           50
4      5   34           64
5      6   40           60
6      7   60           30
7      8   66           40
8      9   70           25


In [26]:
X = df.to_numpy()[:, 1:]
print(X)

[[18 80]
 [20 90]
 [22 85]
 [30 50]
 [34 64]
 [40 60]
 [60 30]
 [66 40]
 [70 25]]


In [32]:
np.random.seed(42)
C = X[np.random.choice(X.shape[0], size=3, replace=True)]
print(C)

[[60 30]
 [30 50]
 [66 40]]


In [35]:
distance = np.linalg.norm(X[:, np.newaxis, :] - C, axis = 2)
print(distance)

[[65.29931087 32.31098884 62.48199741]
 [72.11102551 41.23105626 67.94115101]
 [66.85057965 35.90264614 62.93647591]
 [36.05551275  0.         37.36308338]
 [42.80186912 14.56021978 40.        ]
 [36.05551275 14.14213562 32.80243893]
 [ 0.         36.05551275 11.66190379]
 [11.66190379 37.36308338  0.        ]
 [11.18033989 47.16990566 15.5241747 ]]


In [38]:
label = np.argmin(distance,axis = 1)
print(label)

[1 1 1 1 1 1 0 2 0]


In [45]:
for i in range(3):
    C[i] = X[label == i].mean()

print(C)

[[46 46]
 [49 49]
 [53 53]]
