In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
X = np.array([1.4, 1.0, 1.5, 3.1, 3.7, 4.1])
C = np.array([])
print(X)
print(C)

[1.4 1.  1.5 3.1 3.7 4.1]
[]


In [15]:
np.random.seed(32)
C = np.random.choice(X, size=(2,))
print(C)

[3.1 4.1]


In [ ]:
def clustering(X, C):
    distance = np.abs(X.reshape(-1, 1) - C)
    # print(distance)
    binary_cls = np.argmin(distance, axis=1)
    # print(binary_cls)
    cls = []
    cls.append(np.array(X[binary_cls==0]))
    cls.append(np.array(X[binary_cls==1]))
    return cls
    

In [17]:
def find_centroid(X, C):
    cls = clustering(X, C)
    C = np.array([cls[0].mean(), cls[1].mean()])
    return C

In [18]:
loop = True
step = 0
while(loop):
    if np.all(C == find_centroid(X, C)):
        loop = False
        continue
    C = find_centroid(X, C)
    step += 1
    print(C)
print(step)

[[1.7 2.7]
 [2.1 3.1]
 [1.6 2.6]
 [0.  1. ]
 [0.6 0.4]
 [1.  0. ]]
[[1.7 2.7]
 [2.1 3.1]
 [1.6 2.6]
 [0.  1. ]
 [0.6 0.4]
 [1.  0. ]]
[1.75 3.9 ]
[[0.35 2.5 ]
 [0.75 2.9 ]
 [0.25 2.4 ]
 [1.35 0.8 ]
 [1.95 0.2 ]
 [2.35 0.2 ]]
[[0.35 2.5 ]
 [0.75 2.9 ]
 [0.25 2.4 ]
 [1.35 0.8 ]
 [1.95 0.2 ]
 [2.35 0.2 ]]
[1.3        3.63333333]
[[0.1        2.23333333]
 [0.3        2.63333333]
 [0.2        2.13333333]
 [1.8        0.53333333]
 [2.4        0.06666667]
 [2.8        0.46666667]]
2
