In [603]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [604]:
data = {        # Initialize data
    "Index" : [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "Age" : [18, 20, 22, 30, 34, 40, 60, 66, 70],
    "Expenditure": [80, 90, 85, 50, 64, 60, 30, 40, 25]
}

df = pd.DataFrame(data)

print(df)

   Index  Age  Expenditure
0      1   18           80
1      2   20           90
2      3   22           85
3      4   30           50
4      5   34           64
5      6   40           60
6      7   60           30
7      8   66           40
8      9   70           25


In [605]:
data = df.to_numpy()[:, 1:]     # remove index column
print(data)

[[18 80]
 [20 90]
 [22 85]
 [30 50]
 [34 64]
 [40 60]
 [60 30]
 [66 40]
 [70 25]]


In [606]:
X = data
C = np.array([])

In [607]:
np.random.seed(10)
def K_means(X, C, k):
    C = X[np.random.choice(len(X), size=k, replace=True)]
    print(C)
    return C

In [608]:
def L2_distance(X, C):
    distance = np.array([np.round(np.sqrt(np.sum(np.abs((X - C[i]) ** 2), axis=1)), 2) for i in range (C.shape[0])])
    # X-C[i] = x - xi
    # (x - xi)^2 + (y -yi)^2
    # sqrt()
    # for i -> number of centroids
    return distance.T
    

In [609]:
def find_clustering(X, C):
    distance = L2_distance(X, C)
    # print(distance)
    cls = np.array(np.argmin(distance, axis=1))
    cls_array = []
    for i in range (C.shape[0]):
        cls_array.append(np.array(X[cls == i]))
    return cls , cls_array

In [610]:
def find_centroid(X, C):
    cls, cls_array = find_clustering(X, C)
    # print(cls)
    # print(cls_array)
    C = np.array([np.mean(cls_array[i], axis=0) for i in range(len(cls_array))])
    return C

In [611]:
C = K_means(X, C , 3)
L2_distance(X, C)

loop = True
step = 0

while(loop):
    if np.all(C == find_centroid(X, C)):
        loop = False
        continue
    C = find_centroid(X, C)
    step += 1
    print(f"Step number {step}: ")
    print(C)

print("FINAL RESULT!")
print(C)
print(step)

[[34 64]
 [18 80]
 [20 90]]
Step number 1: 
[[50.         44.83333333]
 [18.         80.        ]
 [21.         87.5       ]]
Step number 2: 
[[53.2 41. ]
 [26.  72. ]
 [21.  87.5]]
Step number 3: 
[[65.33333333 31.66666667]
 [34.66666667 58.        ]
 [20.         85.        ]]
FINAL RESULT!
[[65.33333333 31.66666667]
 [34.66666667 58.        ]
 [20.         85.        ]]
3
