In [585]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [586]:
data = {        # Initialize data
    "Index" : [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "Age" : [18, 20, 22, 30, 34, 40, 60, 66, 70],
    "Expenditure": [80, 90, 85, 50, 64, 60, 30, 40, 25]
}

df = pd.DataFrame(data)

print(df)

   Index  Age  Expenditure
0      1   18           80
1      2   20           90
2      3   22           85
3      4   30           50
4      5   34           64
5      6   40           60
6      7   60           30
7      8   66           40
8      9   70           25


In [587]:
data = df.to_numpy()[:, 1:]     # remove index column
print(data)

[[18 80]
 [20 90]
 [22 85]
 [30 50]
 [34 64]
 [40 60]
 [60 30]
 [66 40]
 [70 25]]


In [588]:
X = data
C = np.array([])

In [589]:
np.random.seed(10)
def K_means(X, C, k):
    C = X[np.random.choice(len(X), size=k, replace=True)]
    print(C)
    return C

In [590]:
def L2_distance(X, C):
    distance = np.array([np.round(np.sqrt(np.sum(np.abs((X - C[i]) ** 2), axis=1)), 2) for i in range (C.shape[0])])
    # X-C[i] = x - xi
    # (x - xi)^2 + (y -yi)^2
    # sqrt()
    # for i -> number of centroids
    return distance.T
    

In [591]:
def find_clustering(X, C):
    distance = L2_distance(X, C)
    print(distance)
    cls = np.array(np.argmin(distance, axis=1))
    cls_array = []
    for i in range (C.shape[0]):
        cls_array.append(np.array(X[cls == i]))
    return cls , cls_array

In [592]:
def find_centroid(X, C):
    cls, cls_array = find_clustering(X, C)
    print(cls)
    print(cls_array)
    C = np.array([np.mean(cls_array[i], axis=0) for i in range(len(cls_array))])
    return C

In [593]:
C = K_means(X, C , 3)
L2_distance(X, C)

loop = True
step = 0

while(loop):
    if np.all(C == find_centroid(X, C)):
        loop = False
        continue
    C = find_centroid(X, C)
    step += 1
    print(C)

print("FINAL RESULT!")
print(C)
print(step)

[[34 64]
 [18 80]
 [20 90]]
[[22.63  0.   10.2 ]
 [29.53 10.2   0.  ]
 [24.19  6.4   5.39]
 [14.56 32.31 41.23]
 [ 0.   22.63 29.53]
 [ 7.21 29.73 36.06]
 [42.8  65.3  72.11]
 [40.   62.48 67.94]
 [53.08 75.69 82.01]]
[1 2 2 0 0 0 0 0 0]
[array([[30, 50],
       [34, 64],
       [40, 60],
       [60, 30],
       [66, 40],
       [70, 25]]), array([[18, 80]]), array([[20, 90],
       [22, 85]])]
[[22.63  0.   10.2 ]
 [29.53 10.2   0.  ]
 [24.19  6.4   5.39]
 [14.56 32.31 41.23]
 [ 0.   22.63 29.53]
 [ 7.21 29.73 36.06]
 [42.8  65.3  72.11]
 [40.   62.48 67.94]
 [53.08 75.69 82.01]]
[1 2 2 0 0 0 0 0 0]
[array([[30, 50],
       [34, 64],
       [40, 60],
       [60, 30],
       [66, 40],
       [70, 25]]), array([[18, 80]]), array([[20, 90],
       [22, 85]])]
[[50.         44.83333333]
 [18.         80.        ]
 [21.         87.5       ]]
[[47.55  0.    8.08]
 [54.22 10.2   2.69]
 [48.96  6.4   2.69]
 [20.66 32.31 38.56]
 [24.97 22.63 26.86]
 [18.17 29.73 33.43]
 [17.89 65.3  69.48]
 [1