In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [101]:
data = {        # Initialize data
    "Index" : [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "Age" : [18, 20, 22, 30, 34, 40, 60, 66, 70],
    "Expenditure": [80, 90, 85, 50, 64, 60, 30, 40, 25]
}

df = pd.DataFrame(data)

print(df)

   Index  Age  Expenditure
0      1   18           80
1      2   20           90
2      3   22           85
3      4   30           50
4      5   34           64
5      6   40           60
6      7   60           30
7      8   66           40
8      9   70           25


In [102]:
X1 = df.to_numpy()[:, 1:]
print(X1)

[[18 80]
 [20 90]
 [22 85]
 [30 50]
 [34 64]
 [40 60]
 [60 30]
 [66 40]
 [70 25]]


In [103]:
np.random.seed(42)

indices = np.random.choice(X1.shape[0], size=3, replace=True)
centroids = X1[indices]

print(centroids)

[[60 30]
 [30 50]
 [66 40]]


# Implement with numpy
X1(9, 2) -> (9, 1,2) -> (9, 3, 2) 
3: 1 point - k centroids  
cenrtoids (3,2) -> broadcasting -> (1, 3, 2) -> (9, 3, 2)

axis=2 -> norm x + y -> euclidean distance to k centroid

In [104]:
distances = np.linalg.norm(X1[:, np.newaxis, :] - centroids[np.newaxis, :, :], axis=2)
print(distances)

[[65.29931087 32.31098884 62.48199741]
 [72.11102551 41.23105626 67.94115101]
 [66.85057965 35.90264614 62.93647591]
 [36.05551275  0.         37.36308338]
 [42.80186912 14.56021978 40.        ]
 [36.05551275 14.14213562 32.80243893]
 [ 0.         36.05551275 11.66190379]
 [11.66190379 37.36308338  0.        ]
 [11.18033989 47.16990566 15.5241747 ]]


# Another way implementation withoud numpy

In [105]:
distances1 = ((X1[:, np.newaxis, :] - centroids) ** 2).sum(axis=2) ** 0.5
print(distances1)

[[65.29931087 32.31098884 62.48199741]
 [72.11102551 41.23105626 67.94115101]
 [66.85057965 35.90264614 62.93647591]
 [36.05551275  0.         37.36308338]
 [42.80186912 14.56021978 40.        ]
 [36.05551275 14.14213562 32.80243893]
 [ 0.         36.05551275 11.66190379]
 [11.66190379 37.36308338  0.        ]
 [11.18033989 47.16990566 15.5241747 ]]
