In [183]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

In [184]:
rng = np.random.default_rng(42)

rolls = rng.integers(1, 7, 10000)

is_even = rolls % 2 == 0

estimated_p = np.mean(is_even)

print(estimated_p)

0.5014


In [185]:
print(rng.random())
print(rng.normal(0.5, 10, 10))      # 0.5 = mean, 10 = std

0.2181491845610315
[-4.91314355  3.22001107 -5.78319985 -2.2836644   4.91358693 -2.98772681
  2.76059589 16.42728456 -1.21858799 12.2933781 ]


In [192]:
np.random.seed(42)
sample_1 = np.random.randint(1, 100, 10)
print(sample_1)

mean_1 = sample_1.mean()
variance = (sample_1 - mean_1) ** 2
variance = np.sum(variance) / variance.size
print(variance)
print(np.sqrt(variance))
print("------------")
print(np.var(sample_1))
print(np.std(sample_1))
print(np.percentile(sample_1, [25, 50, 75]))
print(np.quantile(sample_1, [0.25, 0.5, 0.75]))

[52 93 15 72 61 21 83 87 75 75]
643.6400000000001
25.370061095708856
------------
643.6400000000001
25.370061095708856
[54.25 73.5  81.  ]
[54.25 73.5  81.  ]


In [187]:
np.random.seed(42)
subset = np.random.choice(sample_1, 5, replace=False)
print(subset)
print(subset.var(ddof=0))
print(subset.std(ddof=0))
print("-------------")
print(subset.var(ddof=1))
print(subset.std(ddof=1))

[75 93 21 52 87]
694.24
26.34843448859913
-------------
867.8
29.45844530860378


In [195]:
np.random.seed(42)
sample_2 = np.random.randint(1, 5, (5, 4))
print(sample_2)

print(sample_2.mean(axis = 0))

[[3 4 1 3]
 [3 4 1 1]
 [3 2 3 3]
 [3 3 4 1]
 [4 4 4 3]]
[3.2 3.4 2.6 2.2]


In [188]:
X_train = np.array([1.4, 1., 1.3, 1.9, 2., 3.8, 4.1, 3.9, 4.2, 3.4]).reshape(-1, 1)
y_train = np.array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

classifier = GaussianNB()
cls = classifier.fit(X_train, y_train)

In [189]:
X_test = np.array([1. ,2., 4.3, 4.]).reshape((-1, 1))

cls.predict_proba(X_test)

array([[1.00000000e+00, 2.16339950e-23],
       [1.00000000e+00, 3.92330409e-10],
       [3.24576778e-12, 1.00000000e+00],
       [3.00537144e-10, 1.00000000e+00]])