In [94]:
import numpy as np

In [95]:
data_1 = np.arange(0, 10).reshape(2, -1)
print(data_1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [96]:
np.random.seed(30)
data_2 = np.random.randint(0, 5, (2, 5))
print(data_2)

[[4 4 2 3 1]
 [3 1 1 1 3]]


# Concatenate 2 arrays
axis

In [97]:
# Method 1
new_arr = np.concatenate((data_1, data_2), axis=0)  # Order makes diff
new_arr

# Method 2
new_arr = np.vstack((data_1, data_2))
new_arr

# Method 3
new_arr = np.r_[data_1, data_2]         #r_ = row
new_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [4, 4, 2, 3, 1],
       [3, 1, 1, 1, 3]])

In [98]:
new_arr = np.concatenate((data_1, data_2), axis=1)
new_arr

new_arr = np.hstack((data_1, data_2))
new_arr = np.c_[data_1, data_2]
new_arr

array([[0, 1, 2, 3, 4, 4, 4, 2, 3, 1],
       [5, 6, 7, 8, 9, 3, 1, 1, 1, 3]])

# Make comparison

In [99]:
def max(x, y):
    return x if x >= y else y

In [100]:
print(data_1)
print(data_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[4 4 2 3 1]
 [3 1 1 1 3]]


In [ ]:
vector_max = np.vectorize(max, otypes=[int])

# Method 1
out_1 = vector_max(data_1, data_2)
print(out_1)

# Method 2
out_2 = np.maximum(data_1, data_2)
print(out_2)
    

# Method 3
print(np.where(data_1 > data_2, data_1, data_2)) 
# True -> data1 else data2

[[4 4 2 3 4]
 [5 6 7 8 9]]
[[4 4 2 3 4]
 [5 6 7 8 9]]
[[4 4 2 3 4]
 [5 6 7 8 9]]
