In [282]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import time

In [283]:
x = np.array([1, 2, 3, 4 ,5])
y = np.array([3, 2, 1, 5, 3])

start = time.time()
print(x + y)                        # normal array addition
end = time.time()  

start_1 = time.time()
print(np.add(x, y))                 # np.add -> FASTER
end_1 = time.time()


print(end - start)
print(end_1 - start_1)

[4 4 4 9 8]
[4 4 4 9 8]
0.00032782554626464844
8.893013000488281e-05


In [284]:
print(np.subtract(x, y))
print(np.multiply(x , y))
print(np.divide(x, y))
print(x % y)
print(x // y)

[-2  0  2 -1  2]
[ 3  4  3 20 15]
[0.33333333 1.         3.         0.8        1.66666667]
[1 0 0 4 2]
[0 1 3 0 1]


# Matrix x Vector

In [285]:
X = np.array([[1, 2],
              [3, 4]])

v = np.array([2, 3])            # 1-dimensional -> special case (VECTOR)

print(X.dot(v))                 # 2x2 . 2x1

print(v.dot(X))                 # 1x2 . 2x2 

[ 8 18]
[11 16]


# Matrix x Matrix

In [286]:
v_reshape = v.reshape(1, 2)

print(X.dot(v_reshape.T))
print(v_reshape.dot(X))

print(np.dot(X, v_reshape.T))
print(X@v_reshape.T)

[[ 8]
 [18]]
[[11 16]]
[[ 8]
 [18]]
[[ 8]
 [18]]


In [287]:
start = time.time()
print(v@X)
end = time.time()

start_1 = time.time()
print(np.dot(v, X))
end_1 = time.time()

print(end - start)
print(end_1 - start_1)

[11 16]
[11 16]
0.0004131793975830078
0.00015687942504882812


# Vector operations


In [288]:
color_image = cv2.imread("shibameme.jpg")
color_image = cv2.cvtColor(color_image, cv2.COLOR_BGR2RGB)

print(color_image.shape)

vector = np.array([0.072, 0.715, 0.213])

grayscale_image = np.dot(color_image,vector)                # the last dimensional * vector -> reduce 1 dimen

print(grayscale_image.shape)
cv2.imwrite("output.png", grayscale_image)


(441, 735, 3)
(441, 735)


True

In [289]:
matrix1 = np.arange(9).reshape(3, 3)

matrix2 = np.ones((3, 3))

print(matrix1)
print(matrix1@matrix2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [290]:
np.random.seed(42)
matrix = np.random.randint(1, 10, (3, 3))
print(matrix)

matrix = np.argmax(matrix, axis=0)
print(matrix)

[[7 4 8]
 [5 7 3]
 [7 8 5]]
[0 2 0]


In [ ]:
np.random.seed(42)
matrix = np.random.randint(1, 10, (3, 3))
print(matrix)
_, result = cv2.threshold(matrix.astype(np.uint8), 4,               # <= 4 -> max
                        255, cv2.THRESH_BINARY)
print(result)

[[7 4 8]
 [5 7 3]
 [7 8 5]]
[[255   0 255]
 [255 255   0]
 [255 255 255]]


In [311]:
vector1 = np.array([5, 3, 2, 7])
vector2 = np.array([2, 9, 4, 1])

cosine = (np.dot(vector1, vector2)) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))

print(cosine)

0.552005787925351
