In [1]:
import numpy as np

In [2]:
test = [1, 2, 3]
test_1 = [[1, 2, 3], [5, 6, 2], [3, 4, 6], [1, 1, 3]]
test_2 = [[[1, 2, 3], [1, 1, 3]], [[5, 6, 2], [3, 4, 6]]]

test_np = np.array(test_2)

print(test_np)
print(test_np.shape)

[[[1 2 3]
  [1 1 3]]

 [[5 6 2]
  [3 4 6]]]
(2, 2, 3)


In [3]:
test_np = test_np ** 2 + 1           # rather than go through a function (creating a new array = func(old_array))
print(test_np)

[[[ 2  5 10]
  [ 2  2 10]]

 [[26 37  5]
  [10 17 37]]]


In [4]:
arr = np.ones((2, 3))
arr1 = np.arange(0, 6, 2)           #start ->  < end -> step
print(arr)
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4]


In [5]:
data = np.array([[1, 2, 3], [4, 5, 6 ]])
date_reshape = np.reshape(data, (3, 2))
print(date_reshape)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
np.random.seed(42)                          # like a calibration to ensure all of random times are the same

data = np.random.randint(1, 5, (3, 2))
print(data)
print(data.flatten())                       # flatten -> convert to 1D
print(data.reshape(-1))                     

[[3 4]
 [1 3]
 [3 4]]
[3 4 1 3 3 4]
[3 4 1 3 3 4]


In [7]:
data_repeat = np.repeat(data, 2, axis = 1)          # array, times to repeat, dimension be repeatedly applied  
                                                    # axis = index of shape Ex: (3,2) -> Axis = 0 -> duplicate 3
print(data_repeat)

[[3 3 4 4]
 [1 1 3 3]
 [3 3 4 4]]


# Slicing

In [8]:
data = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])
print(data[0, 1])
print(data[::, 1:3])                               # similar Axis_0, Axis_1 depend on the array shape 

2
[[2 3]
 [5 6]
 [8 9]]


# Indexing

In [9]:
b = data[:, 1:3]                           # when a new array (slicing from the origin) -> have a synchronization 
b[0, 1] = 1000                      
print(data)

[[   1    2 1000]
 [   4    5    6]
 [   7    8    9]]


In [10]:
a = data [1, :]                         # take 1 row
b = data [1:2, :]                       # take 1-> < 2 row -> difference shape 
print(a.shape)
print(b.shape)

(3,)
(1, 3)


In [11]:
a = data[:, 1]                          # similar to column
b = data[:, 1:2]    
print(a.shape)
print(b.shape)

(3,)
(3, 1)


In [12]:
indice = data[[0, 1, 2, 0], [0, 1, 0, 0]]         # take (0,0)  (1,1)  (2,0)   (allow duplicate)
print(indice)
print(indice.shape)

[1 5 7 1]
(4,)


## Condition List

In [13]:
boolean_indice = (data > 5)
print(boolean_indice)

boolean_list = data[boolean_indice]                 # in short: data[data > 5]
print(boolean_list)

[[False False  True]
 [False False  True]
 [ True  True  True]]
[1000    6    7    8    9]


In [14]:
arr = np.arange(5)
print(arr)

condition = arr < 3
out = np.where(condition, arr, arr * 2)                 # T-> arr, F -> arr * 2
print(out)

[0 1 2 3 4]
[0 1 2 6 8]


In [15]:
arr = np.arange(10)
print(arr)

out = np.clip(arr, a_min=3, a_max=7)                    # bound
print(out)

[0 1 2 3 4 5 6 7 8 9]
[3 3 3 3 4 5 6 7 7 7]


# Relational Function

In [16]:
data = np.array([[1, 2, 3],
                [6, 4, 5],
                [3, 9, 7]]) 

print(np.sum(data, axis=0))             # Sum func (axis = 0) -> reduce shape 1 dimensional 
print(np.sum(data, axis=1))
print(np.sum(data))

[10 15 15]
[ 6 15 19]
40


In [17]:
print(np.max(data, axis=0))
print(np.max(data))


print(data.max(axis=0))
print(data.max())

[6 9 7]
9
[6 9 7]
9


In [18]:
def stable_softmax(X):
    exps = np.exp(X - np.max(X))
    return exps / np.sum(exps)

data = stable_softmax(data)
print(data)
print(np.sum(data))

[[2.75787510e-04 7.49668176e-04 2.03780938e-03]
 [4.09304956e-02 5.53934021e-03 1.50574878e-02]
 [2.03780938e-03 8.22110980e-01 1.11260622e-01]]
1.0000000000000002


In [20]:
list = [[1, 3, 4, 2, 3], [4, 2, 4, 5, 1], [6, 1, 2, 4, 1]]

data = np.array(list)
data

array([[1, 3, 4, 2, 3],
       [4, 2, 4, 5, 1],
       [6, 1, 2, 4, 1]])

In [21]:
data = data ** 2 + 1
data


array([[ 2, 10, 17,  5, 10],
       [17,  5, 17, 26,  2],
       [37,  2,  5, 17,  2]])

In [22]:
print(data[data > 10])

[17 17 17 26 37 17]


In [25]:
print(np.max(data, axis=0))
print(np.max(data))
print(np.clip(data, 3, 100))

[37 10 17 26 10]
37
[[ 3 10 17  5 10]
 [17  5 17 26  3]
 [37  3  5 17  3]]


In [38]:
data_1 = np.arange(10)
data_1 = data_1.reshape((2,5))
print(data_1)
print()
print(data_1[::, ::-1])
print()
print(data_1[::-1, ::-1])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[4 3 2 1 0]
 [9 8 7 6 5]]

[[9 8 7 6 5]
 [4 3 2 1 0]]


In [55]:
sample_1 = np.array([[1, 2, 3, 4, 5], [2, 3, 45, 1, 2]])
sample_1 + np.arange(1, 6)
print(sample_1)

# sample_2 = np.arange(1, 6, (5,2))
# sample_2

[[ 1  2  3  4  5]
 [ 2  3 45  1  2]]


In [57]:
np.random.seed(10)

random_sample = np.random.randint(1, 5, (5,2))
random_sample

array([[2, 2],
       [1, 4],
       [1, 2],
       [4, 1],
       [2, 2]])